// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGu4qIW5DDV7_KK4dGVGYOD7OBNuN6HSc',
    appId: '1:307268666238:web:09379594939126f538292f',
    messagingSenderId: '307268666238',
    projectId: 'arvirtualmakeup',
    authDomain: 'arvirtualmakeup.firebaseapp.com',
    storageBucket: 'arvirtualmakeup.firebasestorage.app',
    measurementId: 'G-70WV3JW6F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwPuyD_9RNr-Yh5wQWmbawkZVHhfgDrRE',
    appId: '1:307268666238:android:567b54941db186f038292f',
    messagingSenderId: '307268666238',
    projectId: 'arvirtualmakeup',
    storageBucket: 'arvirtualmakeup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4JTbzIhYHO-5N8u-5VBv30DSJBA5-_Ng',
    appId: '1:307268666238:ios:085fd2ffdadaa97738292f',
    messagingSenderId: '307268666238',
    projectId: 'arvirtualmakeup',
    storageBucket: 'arvirtualmakeup.firebasestorage.app',
    iosBundleId: 'com.example.virtualmakeupapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4JTbzIhYHO-5N8u-5VBv30DSJBA5-_Ng',
    appId: '1:307268666238:ios:085fd2ffdadaa97738292f',
    messagingSenderId: '307268666238',
    projectId: 'arvirtualmakeup',
    storageBucket: 'arvirtualmakeup.firebasestorage.app',
    iosBundleId: 'com.example.virtualmakeupapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGu4qIW5DDV7_KK4dGVGYOD7OBNuN6HSc',
    appId: '1:307268666238:web:09c9112e77cbb77938292f',
    messagingSenderId: '307268666238',
    projectId: 'arvirtualmakeup',
    authDomain: 'arvirtualmakeup.firebaseapp.com',
    storageBucket: 'arvirtualmakeup.firebasestorage.app',
    measurementId: 'G-29K389ZSDB',
  );
}
